config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  has_one_attached :attachment
  mount_uploader :attachment, AttachmentUploader 
  has_many :comments, dependent: :destroy

 

	#validates :title, :description, :author, :b_subject, :image, :attachment, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
     @book = Book.find(params[:id])
    render :show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    byebug
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :author, :b_subject, :image, :attachment)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @books = Book.find(params[:book_id])
      @comment = @books.comments.create(params[:comment].permit(:name, :body))
      redirect_to book_path(@books)
  end
    

  def destroy
      @book = Book.find(params[:book_id])
      @comment = @book.comments.find(params[:id])
      @comment.destroy
      redirect_to book_path(@book)
  
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>subject:</strong>
    <%= book.b_subject %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

</div>

app/views/books/_form.html.erb
  <%= image_tag @book.image if @book.image.attached? %>

<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :title , style: "display: block"%><br>
    <%= form.text_field :title , class: "form-control form-control-lg"%>
  </div>


  <div class="form-group mb-3">
    <%= form.label :author , style: "display: block"%><br>
    <%= form.text_field :author , class: "form-control form-control-lg" %>
  </div>  

  <div class="form-group mb-3">
    <%= form.label :subject , style: "display: block"%><br>
    <%= form.text_field :b_subject , class: "form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description , style: "display: block" %><br>
    <%= form.text_area :description , class: "form-control form-control-lg"%>
  </div>  

   <div class="form-group mb-3">
    <%= form.label :image , style: "display: block" %><br>
    <%= form.file_field :image%>
  </div>     

  <div class="form-group mb-9">
    <%= form.label :attachment , style: "display: block" %><br>
    <%= form.file_field :attachment%>
  </div><br>  
  

  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-lg"%>
    <%= link_to 'Back', books_path, class: "btn btn-outline-primary btn-lg" %>

  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
   <p id="notice"><%= notice %></p>

      <p style = "color:green"><%= notice%></p>
        <div class="col-lg-8 mx-auto">
      <%#if current_user && current_user.admin %> 

              <%= link_to 'Add New Book', new_book_path, class:"btn btn-outline-primary btn-lg mb-3"%> &emsp;

      <%# end  %>              
        <h1>Available Books</h1>
        <div id="books">
            <%@books.each do |book| %>
              <div class="card shadow mb-3">
                <div class="card-body">
                  <%= image_tag book.image if book.image.attached? %>
                  <%#= video_tag book.avatar if book.avatar.attached? %>
                 <p>
                  <strong>Title:</strong> <%= book.title %><br>
                  <strong>Author:</strong><%= book.author %><br>
                  <strong>Subject:</strong><%= book.b_subject %><br>
                  <!-- <strong>Id:</strong><%#= book.user_id %><br> -->
                 </p>
              </div>
           </div> 


          <table>
            <td>
              <%= link_to 'Book Details', book , class:"btn btn-primary btn-lg mb-3"%></td>
               <%#if current_user && current_user.admin %> 
                <td><%= link_to 'Edit', edit_book_path(book), class:"btn btn-primary btn-lg mb-3" %>
                </td>
                <td><%= button_to 'Destroy', book, class:"btn btn-primary btn-lg mb-3", method: :delete, data: { confirm: 'Are you sure?' } %> </td>     
                <%# end %>
            </table>
        <%end%>
            
      </div>
    </div>

app/views/books/new.html.erb
<!-- <h1>New book</h1>

<%#= render "form", book: @book %>

<br>

<div>
</div>
 -->


 <div class="col-lg-8 mx-auto">
  <div class="card shadow">

    <div class="card-header">
      <h1 class="card-title">Add New Book</h1>
    </div>
    <div class="card-body">
      <%= render 'form', book: @book %>
    </div>
  <%#= link_to "Back to books", books_path %>
  </div>
</div>

app/views/books/show.html.erb
<!-- <p style="color: green"><%#= notice %></p>

<%#= render @book %>

<div>
  <%#= link_to "Edit this book", edit_book_path(@book) %> |
  <%#= link_to "Back to books", books_path %>

  <%#= button_to "Destroy this book", @book, method: :delete %>
</div>
 -->

<div class = "container">
 <div class="col-lg-8 ">
    <div class="card shadow">
      <div class="card-body">
        <%= image_tag @book.image if @book.image.attached? %><br>
        <div width="150px" height= "150px">
          </div>
              <p>
                <strong>Title:</strong>
                <%= @book.title %>
              </p>
              <p>
                <strong>author:</strong>
                <%= @book.author %>
              </p>
              <p>
                <strong>Subject:</strong>
                <%= @book.b_subject %>
              </p>
              <!-- <p>
                <strong>User:</strong>
                <%#= @book.user_id %>
              </p> -->
              <p>
                <strong>Description:</strong>
                <%= @book.description %>
              </p>
       </div>
    </div>
</div>


     <div class="mt-5">
        <%= link_to 'Back', books_path, class: "btn btn-outline-primary"%>
        <%#= link_to "Login to Download Book", class: "btn btn-warning" %>
        <%# if current_user%> 
        <%=  link_to "Download book", @book.attachment_url, class: "btn btn-outline-primary" %>
        <%# else %>
        <%#= link_to "Please Signin/Signup to Download this book", class:"btn btn-outline-primary"%>
        <%#end %>
    </div>
    <div>
        <h2><%= @book.comments.count %> Comments</h2><br>
        <%= render @book.comments %><br>
    </div>

    <div>
        <%# if current_user %>
        <h3>Add a comment: </h3><br>
        <%= render  'comments/form' %>  
    </div>    
</div>        
<%#end%>
 -->

<%#= link_to "Continue to Read Book", asset_path("rich-dad-poor-dad.pdf"),class: "btn btn-outline-primary"%>  



        <!-- <iframe src=<%#= @book.avatar if @book.avatar.attached? %> width="600" height="780"><br> -->
          <%#= image_tag @book.avatar.url%>

app/views/books/welcome.html.erb
<!-- <h1>Welcome to books library</h1>

<%#= link_to "Available books", books_path%>


<%#= link_to "Sign in", new_user_session_path%>
<%#= link_to "Sign up", new_user_registration_path%>


<%#= link_to "Sign out", destroy_user_session_path%> -->


<div class="card shadow mb-3">
    <div class="card-body mx-auto ">	
        <h1>Welcome to Open Library</h1>
        <%= link_to 'See Available Books', books_path ,class:"btn btn-outline-primary btn-lg mb-3 mx-auto"%>
        <%= link_to 'Upcoming Books', books_path ,class:"btn btn-outline-primary btn-lg mb-3 mx-auto"%><br>


        <%# if current_user %>
        <%# else %>
        <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-primary" %>
        <%= link_to 'Sign in', new_user_session_path,  class:"btn btn-primary " %>
        <%#end%>
    </div>
</div>

app/views/comments/_comment.html.erb
<!-- <div id="<%= dom_id comment %>">
  <p>
    <strong>Name:</strong>
    <%#= comment.name %>
  </p>

  <p>
    <strong>Body:</strong>
    <%#= comment.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%#= comment.user_id %>
  </p>

</div>
 -->

 <div class="col-lg-8 mb-">
      <div class="card shadow">
            <div class="card-body">
                  <table>
                        <tr>  
                        <td><p><b>Name: </b></p></td>
                        <td><p><%= comment.name %></p></td>
                        </tr>
                        <tr>
                        <td><p><b>Comment: </b></p></td>
                        <td><p><%= comment.body %></p></td>
                        </tr>
                        <p><%= time_ago_in_words(comment.created_at) %></p>
                        <%if current_user && current_user.admin %>
                        <td><p> <%= link_to 'Delete',[comment.book,comment],class: "btn btn-danger" ,method: :delete, data: {cofirm: 'Are you sure?'} %></p></td>
                        <%end%>
                  </table>
            </div>
      </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@books,@book.comments.build]) do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>

<%end%>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<!-- <p style="color: green"><%#= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <%# @comments.each do |comment| %>
    <%#= render comment %>
    <p>
      <%#= link_to "Show this comment", comment %>
    </p>
  <%# end %>
</div>

<%#= link_to "New comment", new_comment_path %>
 -->


 <p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.book_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<!-- <p style="color: green"><%#= notice %></p>

<%#= render @comment %>

<div>
  <%#= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%#= link_to "Back to comments", comments_path %>

  <%#= button_to "Destroy this comment", @comment, method: :delete %>
</div>
 -->


 <p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>book:</strong>
  <%= @comment.book_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Openlibtaskcraft</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>